#!/usr/bin/env python3
"""
SMS Configuration Wizard for EventShield Pro
Interactive setup for SMS functionality
"""

import os
import sys
import getpass

def clear_screen():
    os.system('clear' if os.name != 'nt' else 'cls')

def print_header(title):
    print("\n" + "=" * 70)
    print(f" {title}")
    print("=" * 70 + "\n")

def configure_email_sms():
    """Configure Email-to-SMS method"""
    print_header("Email-to-SMS Configuration")
    
    print("This method sends SMS via email-to-SMS gateways.")
    print("It's free but may be less reliable than Twilio.\n")
    
    print("Supported email providers:")
    print("  - Gmail (recommended)")
    print("  - Outlook/Hotmail")
    print("  - Yahoo Mail")
    print("  - Any SMTP server\n")
    
    email = input("Enter your email address: ").strip()
    
    print("\n⚠️  IMPORTANT for Gmail users:")
    print("  1. Enable 2-factor authentication")
    print("  2. Generate an App Password at:")
    print("     https://myaccount.google.com/apppasswords")
    print("  3. Use the App Password (not your regular password)\n")
    
    password = getpass.getpass("Enter your email password (or App Password): ").strip()
    
    smtp_server = input("SMTP Server [smtp.gmail.com]: ").strip() or "smtp.gmail.com"
    smtp_port = input("SMTP Port [587]: ").strip() or "587"
    
    # Write to .env
    env_content = f"""# EventShield Pro SMS Configuration
# Generated by configure_sms.py

# Email-to-SMS Configuration
SENDER_EMAIL={email}
SENDER_PASSWORD={password}
SMTP_SERVER={smtp_server}
SMTP_PORT={smtp_port}

# Test Configuration
TEST_PHONE=8132702754
TEST_CARRIER=verizon
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n✅ Configuration saved to .env file")
    return True

def configure_twilio():
    """Configure Twilio SMS"""
    print_header("Twilio SMS Configuration")
    
    print("Twilio is a professional SMS service with high reliability.")
    print("Free trial includes $15 credit.\n")
    
    print("To get started:")
    print("  1. Sign up at: https://www.twilio.com/try-twilio")
    print("  2. Get a phone number")
    print("  3. Find your Account SID and Auth Token at:")
    print("     https://console.twilio.com/\n")
    
    has_account = input("Do you have a Twilio account? (y/n): ").strip().lower()
    
    if has_account != 'y':
        print("\n📝 Please sign up for Twilio first and then run this wizard again.")
        return False
    
    account_sid = input("\nEnter your Account SID: ").strip()
    auth_token = getpass.getpass("Enter your Auth Token: ").strip()
    from_number = input("Enter your Twilio phone number (e.g., +12345678900): ").strip()
    
    # Ensure number starts with +
    if not from_number.startswith('+'):
        from_number = '+' + from_number
    
    # Read existing .env or create new
    env_content = ""
    if os.path.exists('.env'):
        with open('.env', 'r') as f:
            env_content = f.read()
    
    # Add or update Twilio config
    twilio_config = f"""
# Twilio SMS Configuration
TWILIO_ACCOUNT_SID={account_sid}
TWILIO_AUTH_TOKEN={auth_token}
TWILIO_PHONE_NUMBER={from_number}
"""
    
    if env_content:
        env_content += "\n" + twilio_config
    else:
        env_content = "# EventShield Pro SMS Configuration\n" + twilio_config
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n✅ Twilio configuration saved to .env file")
    
    # Check if twilio is installed
    try:
        import twilio
        print("✅ Twilio SDK is installed")
    except ImportError:
        print("\n⚠️  Twilio SDK not installed")
        install = input("Install Twilio SDK now? (y/n): ").strip().lower()
        if install == 'y':
            os.system('pip install twilio')
            print("✅ Twilio SDK installed")
    
    return True

def test_configuration():
    """Test the SMS configuration"""
    print_header("Test SMS Configuration")
    
    print("Available tests:")
    print("  1. Test Email-to-SMS")
    print("  2. Test Twilio SMS")
    print("  3. Skip testing")
    
    choice = input("\nSelect test option (1-3): ").strip()
    
    if choice == '1':
        print("\n📤 Running Email-to-SMS test...")
        os.system('python3 send_test_sms.py')
    elif choice == '2':
        print("\n📤 Running Twilio SMS test...")
        os.system('python3 sms_test_twilio.py')
    else:
        print("\n⏭️  Skipping tests")

def main():
    clear_screen()
    
    print("\n")
    print("╔════════════════════════════════════════════════════════════════════╗")
    print("║                                                                    ║")
    print("║           EventShield Pro - SMS Configuration Wizard              ║")
    print("║                                                                    ║")
    print("╚════════════════════════════════════════════════════════════════════╝")
    
    print("\nThis wizard will help you configure SMS functionality.\n")
    
    print("Choose SMS method:")
    print("  1. Email-to-SMS (Free, easy setup)")
    print("  2. Twilio (Reliable, requires signup)")
    print("  3. Exit")
    
    choice = input("\nSelect option (1-3): ").strip()
    
    if choice == '1':
        if configure_email_sms():
            test_configuration()
    elif choice == '2':
        if configure_twilio():
            test_configuration()
    else:
        print("\n👋 Exiting configuration wizard")
        return
    
    print("\n")
    print("=" * 70)
    print("✅ SMS Configuration Complete!")
    print("=" * 70)
    print("\nNext steps:")
    print("  1. Start the backend server:")
    print("     python3 app.py")
    print("\n  2. Send a test SMS:")
    print("     python3 send_test_sms.py")
    print("\n  3. Configure SMS recipients in the web interface")
    print("\n")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⏹️  Configuration cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
